-- Migration 049: Prisma financial schema (source of truth: prisma/schema.prisma)
--
-- Generated by `prisma migrate diff --from-empty --to-schema-datamodel
-- prisma/schema.prisma --script`. The DDL below is the output of that
-- command, copied verbatim and wrapped in a single transaction by
-- node-pg-migrate. DO NOT hand-edit the DDL — re-run the diff command
-- and port the output here if the schema changes. Hand-edited DDL
-- drifts from the Prisma source of truth; that drift is exactly the
-- class of bug this migration exists to repair.
--
-- Tables added:
--   exchange_rates        — FX rate rows with source + spread metadata
--   rate_locks            — time-boxed rate locks for deposit conversion
--   deposit_transactions  — TRON USDT deposit lifecycle
--   custom_rate_configs   — admin-set FX overrides
--   currencies            — currency catalog (seed: USDT)
--   user_balances         — per-user, per-currency balance snapshot
--   ledger_entries        — append-only money-movement log (chained hashes)
--   admin_actions         — admin override trail (balance, rate, kyc, …)
--
-- Enums added:
--   RateSourceType, RateLockStatus, DepositStatus, CurrencyCode,
--   LedgerEntryType, AdminActionType, AdminApprovalStatus
--
-- Companion migration: 050_prisma_financial_schema_seed.sql seeds the
-- currencies table with the USDT row that deposit.service.ts already
-- references via its hardcoded USDT_CURRENCY_ID. The id is fixed so
-- the seed is reproducible across runs.
--
-- Parity gate: scripts/lint-prisma-parity.js (added by WO-2) compares
-- prisma/schema.prisma's model list against the migrated set of tables.
-- This tripwire prevents the same class of bug (Prisma declares a model
-- that doesn't exist in the DB) from regenerating.



BEGIN;

-- CreateEnum
CREATE TYPE "RateSourceType" AS ENUM ('binance_p2p', 'binance_spot', 'bangladesh_bank', 'custom', 'manual_override');

-- CreateEnum
CREATE TYPE "RateLockStatus" AS ENUM ('active', 'consumed', 'expired', 'cancelled');

-- CreateEnum
CREATE TYPE "DepositStatus" AS ENUM ('initiated', 'rate_locked', 'awaiting_payment', 'payment_detected', 'confirming', 'completed', 'failed', 'expired', 'refunded');

-- CreateEnum
CREATE TYPE "CurrencyCode" AS ENUM ('BDT', 'USD', 'USDT');

-- CreateEnum
CREATE TYPE "LedgerEntryType" AS ENUM ('deposit', 'withdrawal', 'bet', 'win', 'loss', 'refund', 'admin_adjustment', 'fee', 'transfer_in', 'transfer_out');

-- CreateEnum
CREATE TYPE "AdminActionType" AS ENUM ('balance_adjustment', 'rate_override', 'seed_rotation', 'config_change', 'withdrawal_approval', 'kyc_manual_review');

-- CreateEnum
CREATE TYPE "AdminApprovalStatus" AS ENUM ('pending', 'approved', 'rejected', 'executed', 'cancelled');

-- CreateTable
CREATE TABLE "exchange_rates" (
    "id" UUID NOT NULL,
    "currency_pair" TEXT NOT NULL,
    "base_currency" TEXT NOT NULL,
    "quote_currency" TEXT NOT NULL,
    "rate" DECIMAL(20,10) NOT NULL,
    "inverse_rate" DECIMAL(20,10) NOT NULL,
    "source_type" "RateSourceType" NOT NULL,
    "source_url" TEXT,
    "source_response" JSONB,
    "buy_spread" DECIMAL(5,4) NOT NULL DEFAULT 0,
    "sell_spread" DECIMAL(5,4) NOT NULL DEFAULT 0,
    "effective_buy_rate" DECIMAL(20,10) NOT NULL,
    "effective_sell_rate" DECIMAL(20,10) NOT NULL,
    "fetched_at" TIMESTAMP(3) NOT NULL,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "is_stale" BOOLEAN NOT NULL DEFAULT false,
    "set_by_id" UUID,
    "custom_justification" TEXT,
    "is_platform_default" BOOLEAN NOT NULL DEFAULT false,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "exchange_rates_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "rate_locks" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "currency_pair" TEXT NOT NULL,
    "locked_rate" DECIMAL(20,10) NOT NULL,
    "locked_inverse_rate" DECIMAL(20,10) NOT NULL,
    "direction" TEXT NOT NULL,
    "input_amount" DECIMAL(20,8) NOT NULL,
    "output_amount" DECIMAL(20,8) NOT NULL,
    "exchange_rate_id" UUID NOT NULL,
    "locked_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "expires_at" TIMESTAMP(3) NOT NULL,
    "status" "RateLockStatus" NOT NULL DEFAULT 'active',
    "consumed_at" TIMESTAMP(3),
    "consumed_by_tx_id" UUID,
    "ip_address" TEXT,
    "device_fingerprint" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "rate_locks_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "deposit_transactions" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "currency_id" UUID NOT NULL,
    "rate_lock_id" UUID,
    "blockchain_network" TEXT,
    "from_address" TEXT,
    "to_address" TEXT NOT NULL,
    "blockchain_tx_id" TEXT,
    "block_number" INTEGER,
    "confirmations" INTEGER NOT NULL DEFAULT 0,
    "required_confirmations" INTEGER NOT NULL DEFAULT 19,
    "crypto_amount" DECIMAL(20,8) NOT NULL,
    "fiat_equivalent" DECIMAL(20,8) NOT NULL,
    "platform_fee" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "net_credit_amount" DECIMAL(20,8) NOT NULL,
    "status" "DepositStatus" NOT NULL DEFAULT 'initiated',
    "status_history" JSONB[],
    "failure_reason" TEXT,
    "retry_count" INTEGER NOT NULL DEFAULT 0,
    "initiated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "locked_at" TIMESTAMP(3),
    "detected_at" TIMESTAMP(3),
    "confirmed_at" TIMESTAMP(3),
    "completed_at" TIMESTAMP(3),
    "expired_at" TIMESTAMP(3),
    "expires_at" TIMESTAMP(3) NOT NULL,
    "ledger_entry_id" UUID,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "deposit_transactions_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "custom_rate_configs" (
    "id" UUID NOT NULL,
    "currency_pair" TEXT NOT NULL,
    "custom_rate" DECIMAL(20,10) NOT NULL,
    "inverse_rate" DECIMAL(20,10) NOT NULL,
    "buy_spread" DECIMAL(5,4) NOT NULL DEFAULT 0,
    "sell_spread" DECIMAL(5,4) NOT NULL DEFAULT 0,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "is_platform_default" BOOLEAN NOT NULL DEFAULT false,
    "set_by_id" UUID NOT NULL,
    "justification" TEXT NOT NULL,
    "valid_from" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "valid_until" TIMESTAMP(3),
    "auto_revert" BOOLEAN NOT NULL DEFAULT true,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "custom_rate_configs_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "currencies" (
    "id" UUID NOT NULL,
    "code" "CurrencyCode" NOT NULL,
    "name" TEXT NOT NULL,
    "symbol" TEXT NOT NULL,
    "decimal_places" INTEGER NOT NULL DEFAULT 2,
    "exchange_rate" DECIMAL(20,10) NOT NULL,
    "exchange_rate_updated_at" TIMESTAMP(3) NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "is_active" BOOLEAN NOT NULL DEFAULT true,
    "min_deposit" DECIMAL(20,8),
    "max_deposit" DECIMAL(20,8),
    "min_withdrawal" DECIMAL(20,8),
    "max_withdrawal" DECIMAL(20,8),
    "withdrawal_fee" DECIMAL(20,8),
    "blockchain_network" TEXT,
    "contract_address" TEXT,
    "updated_by_id" UUID,
    "updated_at" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "currencies_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "user_balances" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "currency_id" UUID NOT NULL,
    "available_balance" DECIMAL(20,8) NOT NULL,
    "reserved_balance" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "total_deposited" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "total_withdrawn" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "total_wagered" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "total_won" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "total_lost" DECIMAL(20,8) NOT NULL DEFAULT 0,
    "version" INTEGER NOT NULL DEFAULT 0,
    "last_updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "user_balances_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "ledger_entries" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "currency_id" UUID NOT NULL,
    "entry_type" "LedgerEntryType" NOT NULL,
    "amount" DECIMAL(20,8) NOT NULL,
    "balance_before" DECIMAL(20,8) NOT NULL,
    "balance_after" DECIMAL(20,8) NOT NULL,
    "session_id" UUID,
    "game_round_id" UUID,
    "reference_id" TEXT,
    "previous_hash" TEXT NOT NULL,
    "current_hash" TEXT NOT NULL,
    "signature" TEXT NOT NULL,
    "metadata" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ledger_entries_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "admin_actions" (
    "id" UUID NOT NULL,
    "admin_id" UUID NOT NULL,
    "action_type" "AdminActionType" NOT NULL,
    "target_type" TEXT NOT NULL,
    "target_id" UUID NOT NULL,
    "old_value" JSONB,
    "new_value" JSONB,
    "justification" TEXT NOT NULL,
    "approval_status" "AdminApprovalStatus" NOT NULL DEFAULT 'pending',
    "approved_by_id" UUID,
    "approved_at" TIMESTAMP(3),
    "executed_at" TIMESTAMP(3),
    "ip_address" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "admin_actions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "exchange_rates_currency_pair_is_platform_default_idx" ON "exchange_rates"("currency_pair", "is_platform_default");

-- CreateIndex
CREATE INDEX "exchange_rates_currency_pair_fetched_at_idx" ON "exchange_rates"("currency_pair", "fetched_at");

-- CreateIndex
CREATE INDEX "exchange_rates_source_type_is_platform_default_idx" ON "exchange_rates"("source_type", "is_platform_default");

-- CreateIndex
CREATE INDEX "rate_locks_user_id_status_idx" ON "rate_locks"("user_id", "status");

-- CreateIndex
CREATE INDEX "rate_locks_expires_at_status_idx" ON "rate_locks"("expires_at", "status");

-- CreateIndex
CREATE INDEX "deposit_transactions_user_id_status_idx" ON "deposit_transactions"("user_id", "status");

-- CreateIndex
CREATE INDEX "deposit_transactions_blockchain_tx_id_idx" ON "deposit_transactions"("blockchain_tx_id");

-- CreateIndex
CREATE INDEX "deposit_transactions_to_address_status_idx" ON "deposit_transactions"("to_address", "status");

-- CreateIndex
CREATE INDEX "deposit_transactions_status_created_at_idx" ON "deposit_transactions"("status", "created_at");

-- CreateIndex
CREATE INDEX "custom_rate_configs_currency_pair_is_platform_default_idx" ON "custom_rate_configs"("currency_pair", "is_platform_default");

-- CreateIndex
CREATE INDEX "custom_rate_configs_currency_pair_is_active_idx" ON "custom_rate_configs"("currency_pair", "is_active");

-- CreateIndex
CREATE UNIQUE INDEX "currencies_code_key" ON "currencies"("code");

-- CreateIndex
CREATE INDEX "currencies_is_default_idx" ON "currencies"("is_default");

-- CreateIndex
CREATE INDEX "currencies_is_active_idx" ON "currencies"("is_active");

-- CreateIndex
CREATE INDEX "user_balances_user_id_idx" ON "user_balances"("user_id");

-- CreateIndex
CREATE INDEX "user_balances_currency_id_idx" ON "user_balances"("currency_id");

-- CreateIndex
CREATE UNIQUE INDEX "user_balances_user_id_currency_id_key" ON "user_balances"("user_id", "currency_id");

-- CreateIndex
CREATE UNIQUE INDEX "ledger_entries_reference_id_key" ON "ledger_entries"("reference_id");

-- CreateIndex
CREATE INDEX "ledger_entries_user_id_currency_id_created_at_idx" ON "ledger_entries"("user_id", "currency_id", "created_at");

-- CreateIndex
CREATE INDEX "ledger_entries_reference_id_idx" ON "ledger_entries"("reference_id");

-- CreateIndex
CREATE INDEX "ledger_entries_entry_type_idx" ON "ledger_entries"("entry_type");

-- CreateIndex
CREATE INDEX "admin_actions_admin_id_created_at_idx" ON "admin_actions"("admin_id", "created_at");

-- CreateIndex
CREATE INDEX "admin_actions_approval_status_idx" ON "admin_actions"("approval_status");

-- CreateIndex
CREATE INDEX "admin_actions_target_type_target_id_idx" ON "admin_actions"("target_type", "target_id");



COMMIT;
