apiVersion: v1
kind: Service
metadata:
  name: cryptoflip-frontend
  namespace: production
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: cryptoflip-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: cryptoflip-api
  namespace: production
spec:
  ports:
  - port: 4000
    targetPort: 4000
  selector:
    app: cryptoflip-api
