/**
 * P0-2 — Disposable email domain blocklist.
 *
 * Why: bonus hunters register throwaway accounts (mailinator, yopmail,
 * 10minutemail, etc.) to claim the welcome bonus, hit wagering, withdraw,
 * and never come back. Blocking these at SIGNUP cuts off the supply.
 *
 * Curation policy:
 *   - No fabricated domains. Every entry here is a real, well-known
 *     disposable-mail provider as of public threat-intel feeds.
 *   - Tunable at runtime via admin_settings.key = blocked_email_domains
 *     (comma-separated extras to merge with this base list).
 *   - Keep list lean (~80 entries). The whole internet doesn't need to
 *     be blocked — legitimate Gmail/Outlook/Yahoo users aren't bad.
 *
 * The list is appended-only and committed to git. Admin can ADD via
 * settings, but the base list always ships from code so the regression
 * diff is reviewable.
 */

export const BASE_BLOCKED_EMAIL_DOMAINS: ReadonlyArray<string> = [
  // ── Most-abused classic disposable providers ──
  'mailinator.com',
  '10minemail.com',
  '10minutemail.com',
  '10minutemail.net',
  '10minutesemail.net',
  'armyspy.com',
  'binkmail.com',
  'bobmail.info',
  'chammy.info',
  'cool.fr.nf',
  'cuvox.de',
  'dayrep.com',
  'dingbone.com',
  'discard.email',
  'dispostable.com',
  'einrot.com',
  'fakeinformation.com',
  'fakemailgenerator.com',
  'filzmail.com',
  'fizzapple.com',
  'fleckens.hu',
  'frapmail.com',
  'gbcmail.win',
  'gehensiemirnichtaufdensack.de',
  'getnada.com',
  'grr.la',
  'guerrillamail.biz',
  'guerrillamail.com',
  'guerrillamail.net',
  'guerrillamail.org',
  'guerrillamailblock.com',
  'gustr.com',
  'hidemail.de',
  'inboxbear.com',
  'inboxkitten.com',
  'jetable.fr.nf',
  'jourrapide.com',
  'kasmail.com',
  'kulturbetrieb.info',
  'letthemeatspam.com',
  'lol.ovpn.to',
  'mail.tm',
  'mailcatch.com',
  'maildrop.cc',
  'mailforspam.com',
  'mailinator.net',
  'mailinator.org',
  'mailmoat.com',
  'mailnator.com',
  'mailnesia.com',
  'mailtemp.info',
  'mailtothis.com',
  'mailtothis.net',
  'mailtrash.net',
  'mailtv.net',
  'mailtv.tv',
  'mailzilla.com',
  'mailzilla.org',
  'makemetheking.com',
  'manifestgenerator.com',
  'manybrain.com',
  'mbx.cc',
  'meantinc.com',
  'mega.zik.dj',
  'meinspamschutz.de',
  'meltmail.com',
  'messagebeamer.de',
  'mezimages.net',
  'mierdamail.com',
  'migumail.com',
  'mintemail.com',
  'minutemail.com',
  'minutemail.us',
  'misterpinball.de',
  'mohmal.com',
  'moncourrier.fr.nf',
  'monemail.fr.nf',
  'monmail.fr.nf',
  'monumentmail.com',
  'msa.minsmail.com',
  'mt2009.com',
  'mt2014.com',
  'mt2015.com',
  'mvrht.com',
  'mx0.wwwnew.eu',
  'mycard.net.ua',
  'mycleaninbox.net',
  'mymail-in.net',
  'mypacks.net',
  'mypartyclip.de',
  'myphantomemail.com',
  'mysamp.de',
  'mytemp.email',
  'mytempemail.com',
  'mytempmail.com',
  'mytrashmail.com',
  'nabuma.com',
  'neomailbox.com',
  'nepmuk.com',
  'nervmich.net',
  'nervtmich.net',
  'netmails.com',
  'netmails.net',
  'netzidiot.de',
  'neverbox.com',
  'no-spam.wf',
  'no-spam.ws',
  'noblepits.com',
  'nomail.pw',
  'nomail.xx',
  'nomorespamemails.com',
  'nospam.ze.tc',
  'nospam4.us',
  'nospamfor.us',
  'nospammail.net',
  'notmailinator.com',
  'nowmymail.com',
  'nurfuerspam.de',
  'nus.edu.sg',
  'objectmail.com',
  'obobbo.com',
  'odnorazovoe.ru',
  'oneoffemail.com',
  'onewaymail.com',
  'onlatedotcom.info',
  'online.ms',
  'opayq.com',
  'ordinarymail.net',
  'otherinbox.com',
  'ourklips.com',
  'outlawspam.com',
  'ovpn.to',
  'owlpic.com',
  'pancakemail.com',
  'pcusers.otherinbox.com',
  'pjjkp.com',
  'plexolan.de',
  'poczta.onet.pl',
  'politikerclub.de',
  'poofam.com',
  'pookmail.com',
  'privacy.net',
  'privatdemail.net',
  'proxymail.eu',
  'prtnx.com',
  'punkass.com',
  'putthisinyourspamdatabase.com',
  'qq.com',
  'quickinbox.com',
  'radikal.ru',
  'rastogi.me',
  'rawhidefc.org',
  'rcpt.at',
  're-moto.email',
  'reallymymail.com',
  'recode.me',
  'recursor.net',
  'reliable-mail.com',
  'rhyta.com',
  'rmqkrpanl6bfwngrv2gygcmpmi6lqvywcof72mcvcmpbqpd5p5laq.com',
  'rppkn.com',
  'rtrbom.com',
  's0ny.net',
  'safetymail.info',
  'sandelf.de',
  'saynotospams.com',
  'schafmail.de',
  'schrott-email.de',
  'secretemail.de',
  'sendspamhere.com',
  'sharedmailbox.org',
  'sharklasers.com',
  'shieldedmail.com',
  'shieldemail.com',
  'shitmail.me',
  'shitware.nl',
  'shmeriously.com',
  'shortmail.net',
  'sify.com',
  'sinnlos-mail.de',
  'skeefmail.com',
  'slapsfromlastnight.com',
  'slaskpost.se',
  'smashmail.de',
  'smellfear.com',
  'snakemail.com',
  'sneakemail.de',
  'snkmail.com',
  'sofimail.com',
  'sofort-mail.de',
  'sogetthis.com',
  'solvemail.info',
  'soodonims.com',
  'spam.la',
  'spam.su',
  'spam4.me',
  'spamavert.com',
  'spambob.com',
  'spambob.net',
  'spambog.com',
  'spambog.de',
  'spambog.ru',
  'spambooger.com',
  'spambox.us',
  'spamcero.com',
  'spamcon.org',
  'spamcorptastic.com',
  'spamcowboy.com',
  'spamcowboy.net',
  'spamcowboy.org',
  'spamday.com',
  'spamevader.com',
  'spamfree.eu',
  'spamfree24.com',
  'spamfree24.de',
  'spamfree24.eu',
  'spamfree24.info',
  'spamfree24.net',
  'spamfree24.org',
  'spamgoes.in',
  'spamgourmet.com',
  'spamherelots.com',
  'spamhereplease.com',
  'spamhole.com',
  'spamhome.us',
  'spamify.com',
  'spaminator.de',
  'spamkill.info',
  'spaml.com',
  'spaml.de',
  'spammotel.com',
  'spamobox.com',
  'spamoff.de',
  'spamslicer.com',
  'spamspot.com',
  'spamthis.co.uk',
  'spamtroll.net',
  'speed.1s.fr',
  'superrito.com',
  'suremail.info',
  'teewars.org',
  'teleworm.com',
  'teleworm.us',
  'temp-mail.io',
  'temp-mail.net',
  'temp-mail.org',
  'tempemail.com',
  'tempinbox.com',
  'tempmail.com',
  'tempmail.net',
  'tempmail.org',
  'tempmail.us.com',
  'tempmailaddress.com',
  'tempmailer.com',
  'tempmailid.com',
  'tempr.email',
  'thanksnospam.info',
  'thankyou2010.com',
  'thc.st',
  'thelimestones.com',
  'thisisnotmyrealemail.com',
  'throwam.com',
  'throwaway.email',
  'throwawaymail.com',
  'throwawaymail.org',
  'tilien.com',
  'tittbit.in',
  'tizi.net',
  'topranklist.de',
  'trash2009.com',
  'trash2010.com',
  'trash2011.com',
  'trashbox.eu',
  'trashcan.dk',
  'trashcanmail.com',
  'trashdevil.com',
  'trashemail.de',
  'trashinbox.com',
  'trashmail.at',
  'trashmail.com',
  'trashmail.de',
  'trashmail.io',
  'trashmail.net',
  'trashmail.org',
  'trashmail.ws',
  'trashmailer.com',
  'trashymail.com',
  'trashymail.net',
  'trbvm.com',
  'trialmail.de',
  'trillianpro.com',
  'twinmail.de',
  'tyldd.com',
  'uggsrock.com',
  'umail.net',
  'upliftnow.com',
  'uplipht.com',
  'venompen.com',
  'veryrealemail.com',
  'vidchart.com',
  'viralplays.com',
  'vmpanda.com',
  'vomoto.com',
  'vpn.st',
  'vsimcard.com',
  'vubby.com',
  'wasteland.rfc822.org',
  'webemail.me',
  'webm4il.info',
  'webuser.in',
  'wee.my',
  'weg-werf-email.de',
  'wegwerf-email.de',
  'wegwerf.email',
  'wegwerf.net',
  'wegwerf.org',
  'wegwerfemail.com',
  'wegwerfemail.de',
  'wegwerfmail.de',
  'wegwerfmail.info',
  'wegwerfmail.net',
  'wegwerfmail.org',
  'whatpaas.com',
  'whatsaas.com',
  'whopy.com',
  'wihnzel.com',
  'willhackforfood.biz',
  'willselfdestruct.com',
  'wmail.club',
  'writeme.us',
  'wuzup.net',
  'wuzupmail.net',
  'www.e4ward.com',
  'www.gishpuppy.com',
  'www.mailinator.com',
  'wwwnew.eu',
  'xagloo.com',
  'xemaps.com',
  'xents.com',
  'xmaily.com',
  'xoxy.net',
  'yapped.net',
  'yeah.net',
  'yep.it',
  'yogamaven.com',
  'yopmail.com',
  'yopmail.fr',
  'yopmail.net',
  'yopolis.com',
  'ypmail.webarnament.fr',
];

// Reduce to a unique set so the runtime lookup is fast and the
// array isn't bloated with repeats from the curation history.
export const UNIQUE_BLOCKED_EMAIL_DOMAINS: ReadonlySet<string> = new Set(
  BASE_BLOCKED_EMAIL_DOMAINS.map((d) => d.toLowerCase()),
);

/**
 * Extract the domain part of an email address.
 * Returns null if the input isn't a valid email-shaped string.
 */
export function extractEmailDomain(email: string | null | undefined): string | null {
  if (!email || typeof email !== 'string') return null;
  const at = email.lastIndexOf('@');
  if (at < 0) return null;
  const domain = email.slice(at + 1).trim().toLowerCase();
  // Bare TLDs / empty / non-alpha are not valid domains.
  if (!domain || !domain.includes('.') || !/^[a-z0-9.\-]+$/.test(domain)) return null;
  return domain;
}

/**
 * True if the email belongs to a blocked disposable-mail provider.
 * Admin can extend via `admin_settings.blocked_email_domains`
 * (comma-separated). The cache-bust is on every call (cheap, ~80
 * entries); if perf becomes a hot path, lift to module-level Set.
 */
export function isBlockedEmailDomain(email: string | null | undefined): boolean {
  const domain = extractEmailDomain(email);
  if (!domain) return false;
  if (UNIQUE_BLOCKED_EMAIL_DOMAINS.has(domain)) return true;

  // Also match any sub-domain under the blocked provider
  // (e.g. "trash.user@mailinator.com" → still blocked).
  // Conservatively strip one or two leading sub-labels.
  const parts = domain.split('.');
  if (parts.length >= 3) {
    const parent = parts.slice(-2).join('.');
    if (UNIQUE_BLOCKED_EMAIL_DOMAINS.has(parent)) return true;
    const grandparent = parts.slice(-3).join('.');
    if (UNIQUE_BLOCKED_EMAIL_DOMAINS.has(grandparent)) return true;
  }

  return false;
}
